# Generated by Django 4.2.1 on 2023-06-02 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("study_field", models.CharField(blank=True, max_length=255, null=True, verbose_name="направление")),
            ],
            options={
                "verbose_name": "направление",
                "verbose_name_plural": "направления",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="дата создания пользователя"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="is_metodist",
            field=models.BooleanField(default=False, verbose_name="методист"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_teacher",
            field=models.BooleanField(default=False, verbose_name="преподаватель"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_update",
            field=models.DateTimeField(auto_now=True, verbose_name="дата последнего обновления пользователя"),
        ),
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="отчество"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="администратор"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="фамилия"),
        ),
        migrations.AddField(
            model_name="user",
            name="study_fields",
            field=models.ManyToManyField(to="accounts.studyfield", verbose_name="направления"),
        ),
    ]
