# Generated by Django 4.2.1 on 2023-06-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_study_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="study_fields",
            field=models.ManyToManyField(blank=True, to="accounts.studyfield", verbose_name="направления"),
        ),
    ]
