# Generated by Django 4.2.2 on 2023-06-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_user_study_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyfield",
            name="short_study_field",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="напр."),
        ),
    ]
