# Generated by Django 4.2.2 on 2023-07-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.AutoField(db_column="ID", primary_key=True, serialize=False)),
                (
                    "study_groups",
                    models.CharField(
                        blank=True, db_column="GroupName", max_length=255, null=True, unique=True, verbose_name="Группа"
                    ),
                ),
                ("course_id", models.IntegerField(blank=True, db_column="KursID", null=True, verbose_name="id курса")),
                (
                    "teacher_fullname",
                    models.CharField(db_column="Prepod", max_length=255, verbose_name="Преподаватель"),
                ),
                (
                    "teacher_id",
                    models.IntegerField(blank=True, db_column="PrepodId", null=True, verbose_name="id преподавателя"),
                ),
                ("study_courses", models.CharField(db_column="Kurs", max_length=255, verbose_name="Курс")),
                ("direction", models.CharField(db_column="Napravlenie", max_length=255, verbose_name="Направления")),
            ],
            options={
                "db_table": "tblGroups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Prepod",
            fields=[
                ("id", models.AutoField(db_column="ID", primary_key=True, serialize=False)),
                ("fullname", models.CharField(db_column="Prepod", max_length=255, verbose_name="ФИО")),
                ("email", models.CharField(db_column="Email", max_length=255, verbose_name="email")),
                ("direction", models.CharField(db_column="Napravlenie", max_length=255, verbose_name="Направления")),
            ],
            options={
                "db_table": "tblPrepods",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="id_crm",
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name="ID в системе CRM"),
        ),
        migrations.AddField(
            model_name="user",
            name="study_courses",
            field=models.TextField(blank=True, null=True, verbose_name="курсы"),
        ),
        migrations.AddField(
            model_name="user",
            name="study_groups",
            field=models.TextField(blank=True, null=True, verbose_name="группы"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(blank=True, null=True, verbose_name="is_active"),
        ),
    ]
